---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-apply
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-apply
  template:
    metadata:
      labels:
        app: pod-apply
    spec:
      containers:
      - name: pod-apply
        image: nginx:1.14.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
